### ISSUE TITLE
`meta-rte` doesn't build with `kas` master branch

### ISSUE THREAD

**Issue by tym2k1** [3mdeb/meta-rte#68]
**meta-rte version**

`v0.7.5`

**Affected component(s) or functionality**

Following [build instructions](https://github.com/3mdeb/meta-rte/blob/31b6e4415b5b8a94af6053d484d266407353528d/README.md#build) doesn't yield a valid image

**Brief summary**

The repository doesn't build with [https://raw.githubusercontent.com/siemens/kas/master/kas-container](https://raw.githubusercontent.com/siemens/kas/master/kas-container) but works with kas `3.0.2`

**How reproducible**

**How to reproduce**

1.  `wget -O ./kas-container https://raw.githubusercontent.com/siemens/kas/master/kas-container`
1. `chmod +x ./kas-container`
1. `mkdir rte-sdk`
1. `cd rte-sdk`
1. `git clone https://github.com/3mdeb/meta-rte.git`
1. `./kas-container build meta-rte/kas.yml`

**Expected behavior**

Image builds correctly

**Actual behavior**

```bitbake
(...)
Traceback (most recent call last):
  File "/work/poky/bitbake/bin/bitbake", line 19, in <module>
    import bb
  File "/work/poky/bitbake/lib/bb/__init__.py", line 75, in <module>
    import bb.msg
  File "/work/poky/bitbake/lib/bb/msg.py", line 19, in <module>
    import bb.event
  File "/work/poky/bitbake/lib/bb/event.py", line 22, in <module>
    import bb.compat
  File "/work/poky/bitbake/lib/bb/compat.py", line 7, in <module>
    from collections import MutableMapping, KeysView, ValuesView, ItemsView, OrderedDict
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.11/collections/__init__.py)
2024-07-04 11:54:07 - ERROR    - Command "/work/poky/bitbake/bin/bitbake -c build core-image-minimal core-image-minimal-swu" failed with error 1
```

**Possible solutions**

- Setting a fixed `kas` version in the README.md instructions

**Comment by artur-rs** [comment]
@tym2k1 bump, linked issue did not close the issue - please manually confirm/close if resolved

**Comment by artur-rs** [comment]
@EduKav1813 let's confirm the changes and close the issue
